-- Gantec Employee Portal - New Tables Setup
-- Run these DDL statements in your Supabase SQL Editor

-- 1. Create Weekly Connect Members Table
CREATE TABLE IF NOT EXISTS public.weekly_connect_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    team TEXT NOT NULL,
    email TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 2. Create Support Tickets Table (Employee Support queries)
CREATE TABLE IF NOT EXISTS public.support_tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    category TEXT NOT NULL,
    priority TEXT NOT NULL,
    subject TEXT NOT NULL,
    description TEXT NOT NULL,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'in-progress', 'resolved')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 3. Create HR Queries Table (Contact HR queries)
CREATE TABLE IF NOT EXISTS public.hr_queries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_name TEXT NOT NULL,
    employee_email TEXT NOT NULL,
    subject TEXT,
    message TEXT NOT NULL,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'in-progress', 'resolved')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 4. Enable Row Level Security (RLS) - Disable restrictions for service role / simple integration
ALTER TABLE public.weekly_connect_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.support_tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hr_queries ENABLE ROW LEVEL SECURITY;

-- 5. Create Permissive Policies for simplicity (since the backend uses service_role key to access them safely)
CREATE POLICY "Allow service role full access weekly_connect_members" ON public.weekly_connect_members FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow service role full access support_tickets" ON public.support_tickets FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow service role full access hr_queries" ON public.hr_queries FOR ALL USING (true) WITH CHECK (true);

-- 6. Enable Realtime replication for dynamic live dashboard updates
DO $$ 
DECLARE
  tables_to_add TEXT[] := ARRAY['weekly_connect_members', 'support_tickets', 'hr_queries'];
  t TEXT;
BEGIN
  IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
    FOREACH t IN ARRAY tables_to_add LOOP
      IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables 
        WHERE pubname = 'supabase_realtime' AND tablename = t
      ) THEN
        EXECUTE format('ALTER PUBLICATION supabase_realtime ADD TABLE public.%I', t);
      END IF;
    END LOOP;
  END IF;
END $$;
