-- Monthly Feedback Rubric Table
-- Run this in your Supabase SQL Editor

CREATE TABLE IF NOT EXISTS public.monthly_feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email TEXT NOT NULL,
    user_name TEXT,
    role TEXT NOT NULL CHECK (role IN ('user', 'admin')),
    selections JSONB NOT NULL DEFAULT '{}',
    is_submitted BOOLEAN NOT NULL DEFAULT FALSE,
    period TEXT NOT NULL DEFAULT to_char(NOW(), 'YYYY-MM'),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_email, role, period)
);

-- Auto-update updated_at on every row change
CREATE OR REPLACE FUNCTION update_monthly_feedback_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_monthly_feedback_updated_at
BEFORE UPDATE ON public.monthly_feedback
FOR EACH ROW EXECUTE FUNCTION update_monthly_feedback_updated_at();

-- Enable Row-Level Security
ALTER TABLE public.monthly_feedback ENABLE ROW LEVEL SECURITY;

-- Policy: Users can only see their own feedback rows
CREATE POLICY "Users can read own feedback"
  ON public.monthly_feedback FOR SELECT
  USING (user_email = auth.jwt() ->> 'email');

-- Policy: Users can insert their own feedback rows
CREATE POLICY "Users can insert own feedback"
  ON public.monthly_feedback FOR INSERT
  WITH CHECK (user_email = auth.jwt() ->> 'email');

-- Policy: Users can update their own NON-submitted feedback rows
CREATE POLICY "Users can update own non-submitted feedback"
  ON public.monthly_feedback FOR UPDATE
  USING (user_email = auth.jwt() ->> 'email' AND is_submitted = FALSE);

-- Add to realtime
ALTER PUBLICATION supabase_realtime ADD TABLE public.monthly_feedback;
