-- ============================================================
-- GANTEC EMPLOYEE PORTAL — ONE-TIME SETUP (Safe to re-run)
-- Run this ENTIRE file in Supabase SQL Editor.
-- It will NOT delete any existing data.
-- ============================================================


-- ── 1. CORE USER & DOCUMENT TABLES ──────────────────────────

CREATE TABLE IF NOT EXISTS public.users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    fullname TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password TEXT,
    role TEXT DEFAULT 'employee',
    points REAL DEFAULT 0,
    profile_image TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.user_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    original_name TEXT NOT NULL,
    hashed_name TEXT NOT NULL,
    folder TEXT DEFAULT 'General',
    size BIGINT,
    upload_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.user_folders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    path TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id, path)
);


-- ── 2. TRAINING RESOURCES TABLES ────────────────────────────

CREATE TABLE IF NOT EXISTS public.resource_uploads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    folder TEXT NOT NULL,
    filename TEXT NOT NULL,
    uploaded_by TEXT NOT NULL,
    size BIGINT,
    upload_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.resource_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    folder TEXT NOT NULL,
    title TEXT NOT NULL,
    url TEXT NOT NULL,
    uploaded_by TEXT NOT NULL,
    upload_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.resource_folders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);


-- ── 3. HR & LEAVE TABLES ────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.leave_balances (
    user_email TEXT PRIMARY KEY,
    pto DECIMAL DEFAULT 12.5,
    sick DECIMAL DEFAULT 4.5,
    floating INTEGER DEFAULT 3,
    celebration INTEGER DEFAULT 1,
    power_apps_link TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS public.hr_queries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_name TEXT NOT NULL,
    employee_email TEXT NOT NULL,
    subject TEXT,
    message TEXT NOT NULL,
    status TEXT DEFAULT 'pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS public.support_tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    category TEXT NOT NULL,
    priority TEXT NOT NULL,
    subject TEXT NOT NULL,
    description TEXT NOT NULL,
    status TEXT DEFAULT 'pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);


-- ── 4. HOLIDAYS & WEEKLY SESSIONS ───────────────────────────

CREATE TABLE IF NOT EXISTS public.holidays (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date TEXT NOT NULL,
    name TEXT NOT NULL,
    type TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.weekly_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    week TEXT NOT NULL,
    name TEXT NOT NULL,
    topic TEXT NOT NULL,
    link TEXT DEFAULT '#',
    filename TEXT DEFAULT '',
    updates TEXT DEFAULT '',
    fun TEXT NOT NULL,
    winners JSONB NOT NULL DEFAULT '[]',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.weekly_connect_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    team TEXT NOT NULL,
    email TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);


-- ── 5. CERTIFICATIONS ───────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.certificate_leaders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    certificate_name TEXT NOT NULL,
    certificate_owner TEXT,
    expiry_date TEXT,
    provider TEXT,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);


-- ── 6. ADMIN & EMAIL TABLES ──────────────────────────────────

CREATE TABLE IF NOT EXISTS public.admin_emails (
    email TEXT PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.main_sub_mails (
    id TEXT PRIMARY KEY,
    main_email TEXT NOT NULL,
    sub_email TEXT NOT NULL,
    period TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);


-- ── 7. MONTHLY FEEDBACK ──────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.monthly_feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email TEXT NOT NULL,
    user_name TEXT,
    role TEXT NOT NULL,
    period TEXT NOT NULL,
    selections JSONB NOT NULL DEFAULT '{}',
    remarks JSONB DEFAULT '{}',
    is_submitted BOOLEAN NOT NULL DEFAULT FALSE,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_email, role, period)
);

-- Add missing columns to monthly_feedback if they don't exist yet
ALTER TABLE public.monthly_feedback ADD COLUMN IF NOT EXISTS user_name TEXT;
ALTER TABLE public.monthly_feedback ADD COLUMN IF NOT EXISTS remarks JSONB DEFAULT '{}';

-- Auto-update updated_at trigger
CREATE OR REPLACE FUNCTION public.update_monthly_feedback_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_monthly_feedback_updated_at ON public.monthly_feedback;
CREATE TRIGGER set_monthly_feedback_updated_at
BEFORE UPDATE ON public.monthly_feedback
FOR EACH ROW EXECUTE FUNCTION public.update_monthly_feedback_updated_at();


-- ── 8. SOCIAL / IDEA HUB TABLES ─────────────────────────────

CREATE TABLE IF NOT EXISTS public.social_posts (
    id TEXT PRIMARY KEY,
    user_email TEXT NOT NULL,
    image_url TEXT,
    caption TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.social_comments (
    id TEXT PRIMARY KEY,
    post_id TEXT NOT NULL REFERENCES public.social_posts(id) ON DELETE CASCADE,
    user_email TEXT NOT NULL,
    comment_text TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.social_likes (
    post_id TEXT NOT NULL REFERENCES public.social_posts(id) ON DELETE CASCADE,
    user_email TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(post_id, user_email)
);

CREATE TABLE IF NOT EXISTS public.social_stories (
    id TEXT PRIMARY KEY,
    user_email TEXT NOT NULL,
    image_url TEXT,
    story_text TEXT,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.public_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uploader_email TEXT NOT NULL,
    folder TEXT NOT NULL,
    filename TEXT NOT NULL,
    original_name TEXT,
    upload_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(folder, filename)
);

CREATE TABLE IF NOT EXISTS public.gantec_idea_hub_posts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    username TEXT NOT NULL,
    user_email TEXT NOT NULL,
    post_content TEXT NOT NULL,
    image_url TEXT,
    tagged_users JSONB DEFAULT '[]',
    likes_count INTEGER NOT NULL DEFAULT 0,
    comments_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    post_visibility TEXT NOT NULL DEFAULT 'public',
    attachments JSONB DEFAULT '[]',
    edited BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS public.reportee_notifications (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    reportee_id UUID NOT NULL,
    reportee_name TEXT NOT NULL,
    assigned_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    notification_message TEXT NOT NULL,
    notification_type TEXT NOT NULL DEFAULT 'reportee_assignment',
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    expires_at TIMESTAMP WITH TIME ZONE DEFAULT (NOW() + INTERVAL '30 days')
);


-- ── 9. FIX USER_ID COLUMN TYPES (safe migration) ────────────

DO $$
BEGIN
    ALTER TABLE public.user_documents ALTER COLUMN user_id TYPE uuid USING user_id::uuid;
EXCEPTION WHEN others THEN
    RAISE NOTICE 'user_documents user_id already uuid, skipping';
END $$;

DO $$
BEGIN
    ALTER TABLE public.user_folders ALTER COLUMN user_id TYPE uuid USING user_id::uuid;
EXCEPTION WHEN others THEN
    RAISE NOTICE 'user_folders user_id already uuid, skipping';
END $$;


-- ── 10. ENABLE REALTIME ON ALL TABLES ───────────────────────

DO $$
DECLARE
  t TEXT;
  all_tables TEXT[] := ARRAY[
    'users','user_documents','user_folders',
    'resource_uploads','resource_links','resource_folders',
    'leave_balances','hr_queries','support_tickets',
    'holidays','weekly_sessions','weekly_connect_members',
    'certificate_leaders','admin_emails','main_sub_mails',
    'monthly_feedback','social_posts','social_comments',
    'social_likes','social_stories','public_documents',
    'gantec_idea_hub_posts','reportee_notifications'
  ];
BEGIN
  IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
    FOREACH t IN ARRAY all_tables LOOP
      IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables
        WHERE pubname = 'supabase_realtime' AND tablename = t
      ) THEN
        EXECUTE format('ALTER PUBLICATION supabase_realtime ADD TABLE public.%I', t);
      END IF;
    END LOOP;
  END IF;
END $$;


-- ── 11. ENABLE RLS ON ALL TABLES ────────────────────────────

DO $$
DECLARE
  tbl TEXT;
  all_tables TEXT[] := ARRAY[
    'users','user_documents','user_folders',
    'resource_uploads','resource_links','resource_folders',
    'leave_balances','hr_queries','support_tickets',
    'holidays','weekly_sessions','weekly_connect_members',
    'certificate_leaders','admin_emails','main_sub_mails',
    'monthly_feedback','social_posts','social_comments',
    'social_likes','social_stories','public_documents'
  ];
BEGIN
  FOREACH tbl IN ARRAY all_tables LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', tbl);
  END LOOP;
END $$;


-- ── 12. CREATE PERMISSIVE POLICIES (drop first to avoid errors) ──

DO $$
DECLARE
  pair TEXT[];
  policy_defs TEXT[][] := ARRAY[
    ARRAY['users',                   'allow_all_users'],
    ARRAY['user_documents',          'allow_all_user_documents'],
    ARRAY['user_folders',            'allow_all_user_folders'],
    ARRAY['resource_uploads',        'allow_all_resource_uploads'],
    ARRAY['resource_links',          'allow_all_resource_links'],
    ARRAY['resource_folders',        'allow_all_resource_folders'],
    ARRAY['leave_balances',          'allow_all_leave_balances'],
    ARRAY['hr_queries',              'allow_all_hr_queries'],
    ARRAY['support_tickets',         'allow_all_support_tickets'],
    ARRAY['holidays',                'allow_all_holidays'],
    ARRAY['weekly_sessions',         'allow_all_weekly_sessions'],
    ARRAY['weekly_connect_members',  'allow_all_weekly_connect_members'],
    ARRAY['certificate_leaders',     'allow_all_certificate_leaders'],
    ARRAY['admin_emails',            'allow_all_admin_emails'],
    ARRAY['main_sub_mails',          'allow_all_main_sub_mails'],
    ARRAY['monthly_feedback',        'allow_all_monthly_feedback'],
    ARRAY['social_posts',            'allow_all_social_posts'],
    ARRAY['social_comments',         'allow_all_social_comments'],
    ARRAY['social_likes',            'allow_all_social_likes'],
    ARRAY['social_stories',          'allow_all_social_stories'],
    ARRAY['public_documents',        'allow_all_public_documents']
  ];
BEGIN
  FOREACH pair SLICE 1 IN ARRAY policy_defs LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', pair[2], pair[1]);
    EXECUTE format(
      'CREATE POLICY %I ON public.%I FOR ALL USING (true) WITH CHECK (true)',
      pair[2], pair[1]
    );
  END LOOP;
END $$;


-- ── 13. INDEXES FOR PERFORMANCE ─────────────────────────────

CREATE INDEX IF NOT EXISTS idx_monthly_feedback_email_period
    ON public.monthly_feedback (user_email, period DESC);

CREATE INDEX IF NOT EXISTS idx_gantec_posts_created_desc
    ON public.gantec_idea_hub_posts (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_gantec_posts_user
    ON public.gantec_idea_hub_posts (user_id);

CREATE INDEX IF NOT EXISTS idx_reportee_notif_user
    ON public.reportee_notifications (user_id, is_read);

CREATE INDEX IF NOT EXISTS idx_user_docs_user
    ON public.user_documents (user_id);

-- ── DONE ─────────────────────────────────────────────────────
-- All tables created, columns added, policies set, realtime enabled.
-- Your existing data is untouched.
