-- Gantec Employee Portal - Supabase Setup
-- Run this in your Supabase SQL Editor

-- 1. Create Users Table (Profile mirroring)
CREATE TABLE IF NOT EXISTS public.users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    fullname TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password TEXT,
    role TEXT DEFAULT 'employee',
    points REAL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 2. Create User Documents Table
CREATE TABLE IF NOT EXISTS public.user_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    original_name TEXT NOT NULL,
    hashed_name TEXT UNIQUE NOT NULL,
    folder TEXT DEFAULT 'General',
    size BIGINT,
    upload_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 3. Create User Folders Table
CREATE TABLE IF NOT EXISTS public.user_folders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    path TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id, path)
);

-- 4. Create Resource Uploads Table (Shared)
CREATE TABLE IF NOT EXISTS public.resource_uploads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    folder TEXT NOT NULL,
    filename TEXT NOT NULL,
    uploaded_by TEXT NOT NULL,
    size BIGINT,
    upload_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 5. Create Resource Links Table (YouTube)
CREATE TABLE IF NOT EXISTS public.resource_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    folder TEXT NOT NULL,
    title TEXT NOT NULL,
    url TEXT NOT NULL,
    uploaded_by TEXT NOT NULL,
    upload_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 6. Create Resource Folders Table (Folder discovery)
CREATE TABLE IF NOT EXISTS public.resource_folders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 7. Enable Realtime (Ultra-Safe Version)
DO $$ 
DECLARE
  tables_to_add TEXT[] := ARRAY['users', 'user_documents', 'user_folders', 'resource_uploads', 'resource_links', 'resource_folders'];
  t TEXT;
BEGIN
  IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
    FOREACH t IN ARRAY tables_to_add LOOP
      IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables 
        WHERE pubname = 'supabase_realtime' AND tablename = t
      ) THEN
        EXECUTE format('ALTER PUBLICATION supabase_realtime ADD TABLE public.%I', t);
      END IF;
    END LOOP;
  END IF;
END $$;

-- 8. Fix existing ID types (Safe & Clean Migration)
TRUNCATE TABLE public.user_documents;
TRUNCATE TABLE public.user_folders;

DO $$ 
BEGIN
    ALTER TABLE public.user_documents ALTER COLUMN user_id TYPE uuid USING NULL;
    ALTER TABLE public.user_folders ALTER COLUMN user_id TYPE uuid USING NULL;
EXCEPTION WHEN others THEN 
    RAISE NOTICE 'Migration already performed or skipped';
END $$;

-- 9. Add Foreign Keys
ALTER TABLE public.user_documents 
  ADD CONSTRAINT user_documents_user_id_fkey 
  FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE public.user_folders 
  ADD CONSTRAINT user_folders_user_id_fkey 
  FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;
