-- Supabase Setup Script for Gantec Employee Portal

-- 1. Users Table
CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    fullname TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 2. Resource Uploads Table (for shared portal resources)
CREATE TABLE IF NOT EXISTS resource_uploads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    folder TEXT NOT NULL,
    filename TEXT NOT NULL,
    uploaded_by TEXT NOT NULL,
    upload_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 3. Resource Links Table (for YouTube/external links)
CREATE TABLE IF NOT EXISTS resource_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    folder TEXT NOT NULL,
    title TEXT NOT NULL,
    url TEXT NOT NULL,
    uploaded_by TEXT NOT NULL,
    upload_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 4. User Folders Table (for private Document Locker)
CREATE TABLE IF NOT EXISTS user_folders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    path TEXT NOT NULL,
    UNIQUE(user_id, path)
);

-- 5. User Documents Table (for private Document Locker)
CREATE TABLE IF NOT EXISTS user_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    original_name TEXT NOT NULL,
    hashed_name TEXT UNIQUE NOT NULL,
    folder TEXT NOT NULL,
    size BIGINT NOT NULL,
    upload_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Enable RLS (Optional, but recommended for production)
-- For now, ensure your Supabase "service_role" key is used in .env to bypass RLS
 